
default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ClarifaiApp_development
  username: ENV['CLARIFAI_DATABASE_USERNAME']
  password: ENV['CLARIFAI_DATABASE_PASSWORD']

test:
  <<: *default
  database: ClarifaiApp_test
  username: ENV['CLARIFAI_DATABASE_USERNAME']
  password: ENV['CLARIFAI_DATABASE_PASSWORD']

production:
  <<: *default
  database: ClarifaiApp_production
  username: ENV['CLARIFAI_DATABASE_USERNAME']
  password: ENV['CLARIFAI_DATABASE_PASSWORD']
